### ISSUE TITLE
Won't instally any version but latest

### ISSUE THREAD

**Issue by pmclanahan** [peterbe/peepin#11]
Was trying to upgrade Django just now and used the following command:

```
$ peepin "Django==1.8.8" requirements/base.txt
```

And it got the wrong hash. The following is the output of `--verbose`.

```
$ peepin --verbose "Django==1.8.8" requirements/base.txt
https://pypi.python.org/pypi/Django/json
* Found URL https://pypi.python.org/packages/py2.py3/D/Django/Django-1.9.1-py2.py3-none-any.whl
*   Re-using /var/folders/z6/4r3j0xc54yg70twp3nvbm5x80000gn/T/Django-1.9.1-py2.py3-none-any.whl
*   Hash n3ygTG288It5Ty6lKDxgFWo36_K4MW0QJ_WU80_2EQE
* Found URL https://pypi.python.org/packages/source/D/Django/Django-1.9.1.tar.gz
*   Re-using /var/folders/z6/4r3j0xc54yg70twp3nvbm5x80000gn/T/Django-1.9.1.tar.gz
*   Hash opqsRqaGyt5tqHzn5yh9XVPN2rxB13fGIwpYPDYkShg
* Editing requirements/base.txt
```

**Comment by pmclanahan** [comment]
Problem seems to be that it always gets and uses latest version in `get_hashes()` while it seems it doesn't need to since `run()` will pass in latest version if it's not provided.

**Comment by peterbe** [comment]
Oops. Seems a rather important bug. I'm on it.

**Comment by pmclanahan** [comment]
I got it working locally with a simple change, but haven't had time yet to add a test. Shall I just PR what I have and you can start from there if you want?

**Comment by peterbe** [comment]
@pmclanahan sure. Or just send me the file and I'll diff i locally and turn it into a thing.
